export const uzbek = {
    CreateAccount: "Hisob yaratish",
    EmailAddress: "E-pochta manzili",
    CreatePassword: "Parol yarating",
    Continue: "Davom eting",
    CustomerAccount: "Mijoz hisobi",
    ShopperAccount: "Xaridor hisobi",
    ConfirmPassword: "Parolni tasdiqlang",
    EmailError: "To'g'ri email kiriting",
    PasswordError: "Parol 6 ta raqamdan iborat bo'lishi kerak",
    ConfirmPasswordError: "Parol 6 ta raqamdan iborat bo'lishi kerak",
    ConfirmPasswordErr: "",
    EmailVerifation: "Elektron pochtani tekshirish",
    EmailVerifationsubtitle: "Olingan 6 raqamli kodni kiriting",
    DigitsCode: "6 raqamli kod",
    Submit: "Yuborish",
    Back: "Orqaga",
    EmailVerified: "Elektron pochta tasdiqlangan",
    VerifySubtitle: "Sizning elektron pochta manzilingiz saytda tasdiqlangan",
    GoToHome: "Ortga qaytish",
    SignIn: "Tizimga kirish",
    VerifationFailed: "Tekshirish amalga oshmadi",
    VerifationFailedSubtitle: "Elektron pochta manzilingizni tekshirish amalga oshmadi.",
    TryAgain: "Qayta urinib ko'ring",
    YourProfile: "Sizning profilingiz",
    YourInformations: "Sizning ma'lumotlaringiz",
    FirstName: "Ism",
    LastName: "Familiya",
    FullName: "To'liq ism",
    Birthday: "Tug'ilgan kun",
    SinginTitle: "Tizimga kiring",
    SinginSubtitle: "Elektron pochta manzilingiz va parolingiz bilan tizimga kiring",
    PlaceholderEmail: "E-pochta manzili",
    PlaceholderPassword: "Parol",
    ResetText: "Yangi parolni yarating va uni tasdiqlang.",
    ResetPassword: "Parolni qayta o'rnating",
    NewPassword: "Yangi parol",
    SavePassword: "Parolni saqlang",
    ForgetPassword: "Parolni unutdingizmi?",
    PasswordChanged: "Sizning parolingiz Muvaffaqiyatli o'zgartirildi",
    Failed: "Tekshirish amalga oshmadi",
    WrongCode: "Siz kodni noto'g'ri kiritdingiz.",
    Gender: "Jins",
    Man: "Erkak",
    Woman: "Ayol",
    HomeAddress: "Uy manzili",
    StreetAddress: "Ko'cha manzili",
    City: "Shahar",
    ZipCode: "Pochta indeksi",
    ProfilePicture: "Profil rasmi",
    UploadPicture: "Rasm yuklash",
    Skip: "O'tkazib yuborish",
    Dashboard: "Boshqaruv paneli",
    Product: "Mahsulot",
    Orders: "Buyurtmalar",
    Customers: "Mijozlar",
    CusChat: "",
    Shopper: "",
    YourShops: "Sizning do'konlaringiz",
    ShopName: "Do'kon nomi",
    CreateShop: "Do'kon yaratish",
    ConfirmLogout: "Chiqishni tasdiqlang",
    AreYouSure: "Haqiqatan ham tizimdan chiqmoqchimisiz?",
    Logout: "Chiqish",
    Cancel: "Bekor qilish",
    YourNewShop: "Sizning yangi do'koningiz",
    ShopInformations: "Do'kon ma'lumotlari",
    BusinessCategory: "Biznes toifasi",
    RegNum: "Registr raqami (ixtiyoriy)",
    Contact: "Aloqa",
    PhoneNumber: "Telefon raqam",
    ShopAddress: "Do'kon manzili",
    ShopLogo: "Do'kon logotipi",
    ShopBanner: "Do'kon banneri",
    Products: "Mahsulotlar",
    SearchProduct: "Mahsulotni qidirish",
    FilterByCategory: "Turkum boʻyicha filtrlash",
    AddNewProduct: "Yangi mahsulot qo'shing",
    ProductId: "Mahsulot identifikatori",
    ProductName: "Mahsulot nomi",
    Category: "Turkum",
    Quantity: "Miqdori",
    PerPrice: "Narx bo'yicha",
    Status: "Status",
    AddProduct: "Mahsulot qo'shing",
    AddPhoto: "Rasm qo'shing",
    AddVideo: "Video qo'shing",
    ProductDescription: "Mahsulot tavsifi",
    Publish: "Nashr qilish",
    UploadProductImage: "Mahsulot rasmini yuklang",
    UploadProductVideo: "Mahsulot videosini yuklang",
    FirstNameError: "Ism kamida 2 ta harfdan iborat bo'lishi kerak",
    LastNameError: "Familiya kamida 2 ta harfdan iborat bo'lishi kerak",
    NickNameError: "Taxallus kamida 2 ta harfdan iborat bo'lishi kerak",
    BirthdayError: "Sanani YYYY-MM-DD formatida kiriting",
    GenderError: "Jinsni tanlang: Erkak yoki Ayol",
    CityError: "Shaharingizni kiriting",
    AddressError: "Manizilingizni kiriting",
    ZipCodeError: "Pochta indeksingizni kiriting",
    Name: "Ism",
    NickName: "Taxallus",
    ContactNumber: "Aloqa raqami",
    Address: "Manzil",
    VerifiedAccount: "Tasdiqlangan hisob"
}

export const rus = {
    CreateAccount: "Зарегистрироваться",
    EmailAddress: "Адрес электронной почты",
    CreatePassword: "Создать пароль",
    Continue: "Продолжать",
    CustomerAccount: "Счет клиента",
    ShopperAccount: "Счет покупателя",
    ConfirmPassword: "Подтвердите пароль",
    EmailError: "Пожалуйста, введите действительный адрес электронной почты",
    PasswordError: "Пароль должен состоять из 6 цифр",
    ConfirmPasswordError: "Пароль должен состоять из 6 цифр",
    ConfirmPasswordErr: "",
    EmailVerifation: "Проверка электронной почты",
    EmailVerifationsubtitle: "Введите 6-значный код, который вы получили, чтобы",
    DigitsCode: "6-значный код",
    Submit: "Отправка",
    Back: "Назад",
    EmailVerified: "Электронная почта проверена",
    VerifySubtitle: "Ваш адрес электронной почты подтвержден на",
    GoToHome: "Иди домой",
    SignIn: "Войти",
    VerifationFailed: "Проверка не удалась",
    VerifationFailedSubtitle: "Проверка вашего адреса электронной почты не удалась.",
    TryAgain: "Попробуйте еще раз",
    YourProfile: "Ваш профиль",
    YourInformations: "Ваша информация",
    FirstName: "Имя",
    LastName: "Фамилия",
    FullName: "Полное имя",
    Birthday: "День рождения",
    SinginTitle: "Войти",
    SinginSubtitle: "Войдите, используя свой адрес электронной почты и пароль",
    PlaceholderEmail: "Адрес электронной почты",
    PlaceholderPassword: "Пароль",
    ResetText: "Создайте новый пароль и подтвердите его.",
    ResetPassword: "Сбросить пароль",
    NewPassword: "Новый пароль",
    SavePassword: "Сохраните пароль",
    ForgetPassword: "Забыли пароль?",
    PasswordChanged: "Ваш пароль успешно изменен",
    Failed: "Проверка не удалась",
    WrongCode: "Вы ввели неверный код.",
    Gender: "Jins",
    Man: "Erkak",
    Woman: "Ayol",
    HomeAddress: "Домашний адрес",
    StreetAddress: "Адрес улицы",
    City: "Shahar",
    ZipCode: "Почтовый индекс",
    ProfilePicture: "Изображение профиля",
    UploadPicture: "Загрузить изображение",
    Skip: "Пропускать",
    Dashboard: "Панель управления",
    Product: "Продукт",
    Orders: "Заказы",
    Customers: "Клиенты",
    CusChat: "КасЧат",
    Shopper: "",
    YourShops: "Ваши магазины",
    ShopName: "Название магазина",
    CreateShop: "Создать магазин",
    ConfirmLogout: "Подтвердить выход",
    AreYouSure: "Вы уверены, что хотите выйти из системы?",
    Logout: "Выход из системы",
    Cancel: "Отмена",
    YourNewShop: "Sizning yangi do'koningiz",
    ShopInformations: "Do'kon ma'lumotlari",
    BusinessCategory: "Biznes toifasi",
    RegNum: "Registr raqami (ixtiyoriy)",
    Contact: "Aloqa",
    PhoneNumber: "Telefon raqam",
    ShopAddress: "Do'kon manzili",
    ShopLogo: "Do'kon logotipi",
    ShopBanner: "Do'kon banneri",
    Products: "",
    SearchProduct: "",
    FilterByCategory: "",
    AddNewProduct: "",
    ProductId: "",
    ProductName: "",
    Category: "",
    Quantity: "",
    PerPrice: "",
    Status: "",
    AddProduct: "",
    AddPhoto: "",
    AddVideo: "",
    ProductDescription: "",
    Publish: "",
    UploadProductImage: "",
    UploadProductVideo: "",
}